### ISSUE TITLE
внешний вид

### ISSUE THREAD

**Issue by DmOsinkin** [DmOsinkin/ineutimetable.ru#1]
## Вынести все данные по атрибутам тегов в отдельный style.css файл.

1. всем тегам определить название  классов, т.е.
`<table>...</table>` 
заменить на
`<table class="mainTable">...</table>` `
2. переписать все исходные заданные свойства атрибутов из внутреннего html-кода в файл style.css.
3. придать стиль всему сайту, добавить фон для таблиц, изменить шрифт (если найдется получше).

**Comment by sadr0b0t** [comment]
А почему wontfix?

**Comment by DmOsinkin** [comment]
потому что внешний вид настроен, но криво, поэтому посчитал, что это всё-таки больше фикс, чем улучшение

**Comment by sadr0b0t** [comment]
wontfix - это статус тикета, который по какой-то причине не собираешься исправлять (дословно: не буду исправлять).

для багов статус: bug
для улучшений статус: enhancement

**Comment by DmOsinkin** [comment]
Понял, исправлю
